stages:
  - setup-docker-image
  - build
  - test
  - doc
  - deploy

variables:
  dind_image: "docker:20.10.7"
  dind_service: "docker:20.10.7-dind"
  SHOW_INFO: >
    echo "=========== INFO: ============" &&
    opam config exec -- ocamlc -version &&
    git status &&
    git log --graph  --decorate --all --oneline -n 20

docker:images:
  image: "$dind_image"
  services:
    - "$dind_service"
  stage: setup-docker-image
  variables:
    DOCKER_DRIVER: overlay2
  # https://forum.gitlab.com/t/pipeline-stuck-with-fetch-https-dl-cdn-alpinelinux-org-alpine-v3-14-main-x86-64-apkindex-tar-gz/59074/4
    FF_NETWORK_PER_BUILD: "true"
  before_script:
    - apk add git bash
    - git --version
    - bash --version
    - docker --version
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull ocaml/opam:ubuntu-21.04-ocaml-4.12
    - docker build . --target build_step -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-build"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-build"
    - docker build . --target run_image -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-run"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-run"

lint:
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-build"
  stage: build
  script:
     - bash -c "$SHOW_INFO"
     - opam install ocamlformat.0.18.0
     - opam exec -- ocamlformat --version
     - opam exec -- make fmt
     - git diff --exit-code

docker:test:
  image: "$dind_image"
  services:
    - "$dind_service"
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  # https://forum.gitlab.com/t/pipeline-stuck-with-fetch-https-dl-cdn-alpinelinux-org-alpine-v3-14-main-x86-64-apkindex-tar-gz/59074/4
    FF_NETWORK_PER_BUILD: "true"
  artifacts:
     paths:
     - mini-net-root
  script:
    - docker run "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-run" cat /usr/bin/flextesarl
    - docker run "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-run" flextesa mini --root /root --protocol-kind Granada --keep-root --time-between-blocks 2 --until-level 10 --number-of-boot 1 --size 1
    - docker run "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-run" flextesa mini --root /root --protocol-kind Hangzhou --keep-root --time-between-blocks 3 --minimal-block 2 --until-level 10 --number-of-boot 1 --size 1


makewebsite:
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-build"
  stage: build
  artifacts:
     paths:
     - testweb
  script:
     - bash -c "$SHOW_INFO"
     - opam exec -- bash src/scripts/build-doc.sh testweb/

pages:
  image: docker:latest
  stage: deploy
  script:
     - cp -r testweb public
  artifacts:
     paths:
     - public
  only:
  - master
